[plugins]

jmh = { id = "me.champeau.jmh", version = "0.7.2" }

[libraries]

assertj = "org.assertj:assertj-core:3.24.2"
commons-math = "org.apache.commons:commons-math3:3.6.1"
equalsverifier = "nl.jqno.equalsverifier:equalsverifier:3.15.3"
guava = "com.google.guava:guava:32.1.3-jre"
prngine = "io.jenetics:prngine:2.0.0"
rxjava = "io.reactivex.rxjava2:rxjava:2.2.21"
testng = "org.testng:testng:7.8.0"
